test:
  image: python:3.9-slim-buster
  script:
    - python -m pip install -e src/
    - pytest tests/
  only:
    changes:
      - Dockerfile
      - requirements.txt
      - tests/**/*.py
      - src/**/*.py
