test:
  image: python:3.9-slim-buster
  script:
    - python -m pip install -e src/
    - coverage run -m pytest tests/
    - coverage report
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
  only:
    changes:
      - Dockerfile
      - requirements.txt
      - tests/**/*.py
      - src/**/*.py
